# Generated by Django 3.2.9 on 2021-11-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='id',
        ),
        migrations.AlterField(
            model_name='city',
            name='key',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
